# -*- coding: utf-8 -*-
"""tabular_neural_network

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1czfwAFpTCvGfXSRgNnCZ6JDlZcCrQTVA
"""

# Bismillah i am writing my first code for pytorch to understand this library best of luck for me

!pip install opendatasets --quiet
import opendatasets as od
od.download("https://www.kaggle.com/datasets/mssmartypants/rice-type-classification")

# Headers that are required for the neural network training
import torch
import torch.nn as nn
from torch.optim import Adam
from torch.utils.data import DataLoader , Dataset
from torchsummary import summary
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

data_df= pd.read_csv("/content/rice-type-classification/riceClassification.csv")
data_df.head()

# now drop the missing values and id col as it not giving any valuable info for our model

data_df.dropna(inplace = True)
data_df.drop(['id'] , axis = 1 ,inplace = True )
print(data_df.shape)
data_df.head()

# check how many classes are here
print(data_df['Class'].unique())
print(data_df['Class'].value_counts())

original_df = data_df.copy()

for col in data_df :
  data_df[col] = data_df[col] / data_df[col].abs().max()

data_df.head()

#not take the last col in x and take the last col only in y
X = np.array(data_df.iloc[:,:-1])
Y = np.array(data_df.iloc[:,-1])

x_train , x_test , y_train , y_test = train_test_split(X,Y,test_size=0.3)


x_val , x_test , y_val , y_test = train_test_split(x_test,y_test,test_size=0.5)

print(x_train.shape)
print(x_test.shape)
print(x_val.shape)

class dataset(Dataset):
  def __init__ (self,X,Y):
    self.X = torch.tensor(X,dtype=torch.float32).to(device)
    self.Y= torch.tensor(Y,dtype=torch.float32).to(device)

  def __len__(self):
    return len(self.X)

  def __getitem__ (self,index):
    return self.X[index] , self.Y[index]

training_data = dataset(x_train,y_train)
testing_data = dataset(x_test,y_test)
validation_data = dataset(x_val,y_val)

train_dataloader = DataLoader(training_data,batch_size=8,shuffle=True)
test_loader = DataLoader(testing_data, batch_size=8 , shuffle= True )
validation_loader = DataLoader(validation_data,batch_size=8 , shuffle =True)

for x, y in train_dataloader:
  print(x)
  print("===================")
  print(y)
  break

#now we will create a custom Model for training
# total parameters are fetures * shape of output + bais
HIDDEN_NEURONS = 10
class mymodel(nn.Module):
  def __init__(self):
    super(mymodel,self).__init__()
    self.input_layer= nn.Linear(X.shape[1] , HIDDEN_NEURONS)
    self.linear = nn.Linear (HIDDEN_NEURONS,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,x):
    x = self.input_layer(x)
    x= self.linear(x)
    x= self.sigmoid(x)
    return x
model = mymodel().to(device)

summary(model, (X.shape[1] ,))

# now we have to do training for that define the loss and the optimizer
losscal = nn.BCELoss()
optimizer  = Adam(model.parameters(), lr=1e-3)
# define the lists we need in the training loop
total_loss_train= []
total_loss_val=[]
total_acc_train = []
total_acc_val = []
epochs= 10

for epoch in range(epochs):
  train_loss = 0
  train_acc = 0
  val_loss = 0
  val_acc = 0
  for data in train_dataloader:
    input , label = data
    prediction = model(input).squeeze(1)

    batch_loss = losscal(prediction,label)
    train_loss += batch_loss.item()

    acc = (prediction.round()==label).sum().item()
    train_acc+=acc

    batch_loss.backward()
    optimizer.step()
    optimizer.zero_grad()

  with torch.no_grad():
    for data in validation_loader:
      input,label = data
      prediction = model(input).squeeze(1)

      batch_loss = losscal(prediction,label)
      val_loss += batch_loss.item()

      acc = (prediction.round()==label).sum().item()
      val_acc+=acc

  total_loss_train.append(round(train_loss/1000 ,4))
  total_loss_val.append(round(val_loss/1000 ,4))
  total_acc_train.append(round(train_acc/training_data.__len__() *100  ,4 ))
  total_acc_val.append(round(val_acc/validation_data.__len__() * 100 ,4 ) )

  print (f"Epoch : {epoch+1} Train Loss {round(train_loss/1000 ,4)} Validation Loss : {round(val_loss/1000 ,4)} Train Accuracy {round(train_acc/training_data.__len__() *100  ,4 )} Validation Accuracy {round(val_acc/validation_data.__len__() * 100 ,4 )}")

  print("="*50)

with torch.no_grad():
  test_loss=0
  test_acc= 0
  for data in test_loader:
    input,label= data
    prediction=  model(input).squeeze(1)
    loss = losscal(prediction,label)
    test_loss += loss.item()

    acc = (prediction.round()==label).sum().item()
    test_acc += acc

  print (f"Loss {round(test_loss/1000,4)} Accuracy {round(test_acc/testing_data.__len__(),4) * 100}")

# now we will visualize our model epochs here

fig ,axs = plt.subplots(nrows=1 ,ncols=2 ,figsize=(15,5))

axs[0].plot(total_loss_train,label= "Training Loss")
axs[0].plot(total_loss_val,label ="Validation Loss")
axs[0].set_title("Training and validation loss")
axs[0].set_xlabel('Epochs')
axs[0].set_ylabel('Loss')
axs[0].set_ylim([0,0.2])
# show a box at top and show which line color correspond to what
axs[0].legend()

axs[1].plot(total_acc_train,label="Training accuracy")
axs[1].plot(total_acc_val,label="Validation accuracy")
axs[1].set_title("Training and validation accuracy")
axs[1].set_ylabel('Accuracy')
axs[1].set_xlabel('Epoch')
axs[1].set_ylim([95,100])
axs[1].legend()

plt.tight_layout()
plt.show()

# i want to do a single prediction with a model
#inference
original_df.columns

Area = 8183/original_df['Area'].abs().max()

MajorAxisLength = 8183/original_df['MajorAxisLength'].abs().max()


MinorAxisLength = 8183/original_df['MinorAxisLength'].abs().max()

Eccentricity = 8183/original_df['Eccentricity'].abs().max()

ConvexArea = 8183/original_df['ConvexArea'].abs().max()

EquivDiameter = 8183/original_df['EquivDiameter'].abs().max()

Extent = 8183/original_df['Extent'].abs().max()

Perimeter = 8183/original_df['Perimeter'].abs().max()

Roundness = 8183/original_df['Roundness'].abs().max()

AspectRation = 8183/original_df['AspectRation'].abs().max()

prediction = model (torch.tensor([Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,EquivDiameter,Extent,Perimeter,Roundness,AspectRation], dtype= torch.float32 ,device = device ))

print(prediction.item())